jobs:
  build:
    executor:
      name: node/default
      tag: '10.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test:debug
  build-12:
    executor:
      name: node/default
      tag: '12.14'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
orbs:
  node: circleci/node@1.1
version: 2.1

